import { createHash } from "node:crypto";
import {
	closeSync,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readFileSync,
	statSync,
	unlinkSync,
	writeSync,
} from "node:fs";
import { basename, resolve } from "node:path";
import { $ } from "bun";

export const MIN_SLOT = 1;
export const MAX_SLOT = 9;

// AggregateError's own .message is empty; the detail is in .errors.
export function describeError(error: unknown): string {
	if (error instanceof AggregateError) {
		return error.errors.map((e) => describeError(e)).join("; ");
	}
	if (error instanceof Error) return error.message;
	return String(error);
}

export interface WorktreeEntry {
	path: string;
}

export async function listWorktrees(cwd: string): Promise<WorktreeEntry[]> {
	const output = await $`git worktree list --porcelain`.cwd(cwd).quiet().text();
	const entries: WorktreeEntry[] = [];
	for (const line of output.split("\n")) {
		if (line.startsWith("worktree ")) {
			entries.push({ path: line.slice("worktree ".length) });
		}
	}
	return entries;
}

export async function worktreeRoot(cwd: string): Promise<string> {
	const output = await $`git -C ${cwd} rev-parse --show-toplevel`
		.quiet()
		.text();
	return output.trim();
}

export async function isLinkedWorktree(cwd: string): Promise<boolean> {
	const gitDir = await $`git rev-parse --git-dir`.cwd(cwd).quiet().text();
	const commonDir = await $`git rev-parse --git-common-dir`
		.cwd(cwd)
		.quiet()
		.text();
	return resolve(cwd, gitDir.trim()) !== resolve(cwd, commonDir.trim());
}

export async function gitCommonDir(cwd: string): Promise<string> {
	const output = await $`git rev-parse --git-common-dir`
		.cwd(cwd)
		.quiet()
		.text();
	return resolve(cwd, output.trim());
}

export async function mainWorktreePath(cwd: string): Promise<string> {
	const [main] = await listWorktrees(cwd);
	if (!main) throw new Error("worktree: `git worktree list` returned nothing.");
	return main.path;
}

export function slugFor(worktreePath: string): string {
	const abs = resolve(worktreePath);
	// Avoids collisions between names that collide once sanitized, e.g. "x" and "x-test".
	const hash = createHash("sha256").update(abs).digest("hex").slice(0, 6);
	const base = basename(abs)
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "_")
		.slice(0, 30);
	return `${base}_${hash}`;
}

export function databasesFor(slug: string): {
	dev: string;
	test: string;
	e2e: string;
} {
	const dev = `bluprint_wt_${slug}`;
	return { dev, test: `${dev}_test`, e2e: `${dev}_e2e` };
}

// Minimal KEY=VALUE reader; no multiline values, unlike dotenv.
export function parseEnvFile(path: string): Record<string, string> {
	if (!existsSync(path)) return {};
	const result: Record<string, string> = {};
	for (const line of readFileSync(path, "utf8").split("\n")) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#")) continue;
		const eq = trimmed.indexOf("=");
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		let value = trimmed.slice(eq + 1).trim();
		const quoted =
			(value.startsWith('"') && value.endsWith('"')) ||
			(value.startsWith("'") && value.endsWith("'"));
		if (quoted) value = value.slice(1, -1);
		result[key] = value;
	}
	return result;
}

// process.env wins, then .env.local, then .env (ADR 0049)
export function resolveDatabaseUrl(cwd: string): string {
	const sources = [
		process.env as Record<string, string | undefined>,
		parseEnvFile(resolve(cwd, ".env.local")),
		parseEnvFile(resolve(cwd, ".env")),
	];
	for (const source of sources) {
		if (source.DATABASE_URL) return source.DATABASE_URL;
	}
	throw new Error(
		`worktree: no DATABASE_URL via process env, .env.local or .env in ${cwd}.`,
	);
}

export function urlWithDatabase(baseUrl: string, database: string): string {
	const url = new URL(baseUrl);
	url.pathname = `/${database}`;
	return url.toString();
}

export function envLocalContents(
	slot: number,
	slug: string,
	baseUrl: string,
): string {
	const apiPort = 3000 + 10 * slot;
	const webPort = 5173 + 10 * slot;
	const e2eApiPort = 3100 + 10 * slot;
	const e2eWebPort = 5273 + 10 * slot;
	const { dev, test, e2e } = databasesFor(slug);
	return `# Generated by \`bun run worktree:setup\` — safe to delete and regenerate.
SLOT=${slot}
SLUG=${slug}
PORT=${apiPort}
WEB_PORT=${webPort}
CORS_ORIGIN=http://localhost:${webPort}
BETTER_AUTH_URL=http://localhost:${apiPort}
DATABASE_URL=${urlWithDatabase(baseUrl, dev)}
DATABASE_URL_TEST=${urlWithDatabase(baseUrl, test)}
DATABASE_URL_E2E=${urlWithDatabase(baseUrl, e2e)}
E2E_API_PORT=${e2eApiPort}
E2E_WEB_PORT=${e2eWebPort}
`;
}

const LOCK_STALE_MS = 10 * 60 * 1000;
const LOCK_RETRY_MS = 500;
const LOCK_MAX_WAIT_MS = 5 * 60 * 1000;

function lockPath(commonDir: string): string {
	return resolve(commonDir, "bluprint-worktree-setup.lock");
}

async function acquireLock(path: string): Promise<void> {
	const start = Date.now();
	for (;;) {
		try {
			const fd = openSync(path, "wx");
			writeSync(fd, `${process.pid}\n${new Date().toISOString()}\n`);
			closeSync(fd);
			return;
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
			let mtimeMs: number;
			try {
				mtimeMs = statSync(path).mtimeMs;
			} catch (statError) {
				// Released between our open() and stat(): try again now.
				if ((statError as NodeJS.ErrnoException).code === "ENOENT") continue;
				throw statError;
			}
			if (Date.now() - mtimeMs > LOCK_STALE_MS) {
				try {
					unlinkSync(path);
				} catch {
					// another process cleared it first
				}
				continue;
			}
			if (Date.now() - start > LOCK_MAX_WAIT_MS) {
				throw new Error(
					`worktree: timed out waiting for the setup lock at ${path}.`,
				);
			}
			await Bun.sleep(LOCK_RETRY_MS);
		}
	}
}

function releaseLock(path: string): void {
	try {
		unlinkSync(path);
	} catch {
		// already gone
	}
}

// Serializes slot selection only, not install/build/DB work (ADR 0049)
export async function withSetupLock<T>(
	commonDir: string,
	fn: () => Promise<T>,
): Promise<T> {
	const path = lockPath(commonDir);
	await acquireLock(path);
	try {
		return await fn();
	} finally {
		releaseLock(path);
	}
}

function slotsDir(commonDir: string): string {
	return resolve(commonDir, "bluprint-slots");
}

interface Reservation {
	worktreePath: string;
	pid: number;
}

function readReservation(path: string): Reservation | null {
	try {
		const [worktreePath, pidLine] = readFileSync(path, "utf8").split("\n");
		const pid = Number(pidLine);
		return worktreePath && Number.isInteger(pid) ? { worktreePath, pid } : null;
	} catch {
		return null;
	}
}

function isProcessAlive(pid: number): boolean {
	try {
		process.kill(pid, 0);
		return true;
	} catch {
		return false;
	}
}

// A reservation is stale once its worktree or its process is gone.
export function cleanStaleReservations(commonDir: string): void {
	const dir = slotsDir(commonDir);
	if (!existsSync(dir)) return;
	for (const entry of readdirSync(dir)) {
		const entryPath = resolve(dir, entry);
		const reservation = readReservation(entryPath);
		const stale =
			!reservation ||
			!existsSync(reservation.worktreePath) ||
			!isProcessAlive(reservation.pid);
		if (stale) unlinkSync(entryPath);
	}
}

// A worktree mid-setup has databases but no .env.local yet.
export function reservedWorktreePaths(commonDir: string): string[] {
	const dir = slotsDir(commonDir);
	if (!existsSync(dir)) return [];
	return readdirSync(dir)
		.map((entry) => readReservation(resolve(dir, entry)))
		.filter((r): r is Reservation => r !== null)
		.map((r) => r.worktreePath);
}

export function reservedSlots(commonDir: string): Set<number> {
	const dir = slotsDir(commonDir);
	if (!existsSync(dir)) return new Set();
	return new Set(readdirSync(dir).map(Number).filter(Number.isInteger));
}

export function reserveSlot(
	commonDir: string,
	slot: number,
	worktreePath: string,
): void {
	const dir = slotsDir(commonDir);
	mkdirSync(dir, { recursive: true });
	const fd = openSync(resolve(dir, String(slot)), "w");
	writeSync(fd, `${worktreePath}\n${process.pid}\n`);
	closeSync(fd);
}

export function releaseSlotReservation(commonDir: string, slot: number): void {
	try {
		unlinkSync(resolve(slotsDir(commonDir), String(slot)));
	} catch {
		// already gone
	}
}

export async function pickSlot(
	selfPath: string,
	commonDir: string,
): Promise<number> {
	const used = new Set<number>();
	for (const worktree of await listWorktrees(selfPath)) {
		if (resolve(worktree.path) === resolve(selfPath)) continue;
		const env = parseEnvFile(resolve(worktree.path, ".env.local"));
		if (env.SLOT) used.add(Number(env.SLOT));
	}
	for (const slot of reservedSlots(commonDir)) used.add(slot);
	for (let slot = MIN_SLOT; slot <= MAX_SLOT; slot++) {
		if (!used.has(slot)) return slot;
	}
	throw new Error(
		`worktree: no free slot in ${MIN_SLOT}-${MAX_SLOT} — remove an unused worktree first.`,
	);
}
